version: "3.9"

services:
  app:
    container_name: app
    build: ./
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 5000:5000
    command: /
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  postgres_data: null